### ISSUE TITLE
Provide maven repository branch

### ISSUE THREAD

**Issue by kuzeko** [forons/spark-core#2]
To ease adoption, would be great if you could provide a `maven` branch to be added in any project using this library.

Instructions can be found here: https://gist.github.com/fernandezpablo85/03cf8b0cd2e7d8527063

A running example is https://github.com/mutandon/Grava/tree/maven

**Comment by forons** [comment]
Thank you for the suggestion!
How does it work for including this project in the pom.xml?

**Comment by kuzeko** [comment]
You get your repository URL as follows:

`The repository url you just created is https://raw.github.com/YOUR_ORGANIZATION/YOUR_ARTIFACT/repository/`


Then is like a normal library (See https://github.com/mutandon/Grava/blob/maven/README.md)

Note, in `Grava` the branch name is `maven` and not `repository`

**Comment by forons** [comment]
Nice! Thank you!
